### ISSUE TITLE
Creating an Oranisation License results in an error code

### ISSUE THREAD

**Issue by Sebuschka** [jakeswenson/BitBetter#112]
If i generate an Organisation License either with ./run.sh interactive or the command directly (./run.sh "bitbetter path" "Org Name" "Email of user" "install id"
I get this error:
Specify --help for a list of available options and commands.
Oops: Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized command or argument 'Sebuschka'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at bitwardenSelfLicensor.Program.Main(String[] args) in /licenseGen/Program.cs:line 286

Already did a rebuild at /Bitbetter and also a rebuild at /bitbetter/src/licensegen. No changes. Do you have any idea on what i am doing wrong?

**Comment by Ikallin** [comment]
Hi @Sebuschka !

I finally solved my issue. Indeed, the SSO and Single Org policies were not allowing me to create new Org.

I don't think it would help you but there it is.

Hope you will find out soon !

**Comment by Sebuschka** [comment]
Hi @Ikallin 

Yes I was running the latest version when the error occurred.
Haven't been testing a lot since than but gonna try out ceating a new user without a license and than just an organization license.
I'm gonna let you know when I find something that works

**Comment by captainhook** [comment]
@Sebuschka any update?
