### ISSUE TITLE
Unhandled Server Error when editing or adding anything in my Organization

### ISSUE THREAD

**Issue by jlevickas** [jakeswenson/BitBetter#157]
Hi, I am getting an error when editing an entry or adding an user to my organization.

Here are some logs from trying to add an user:

> 2023-02-09 20:05:35.945 +00:00 [Error] Procedure or function 'Event_Create' expects parameter '@InstallationId', which was not supplied.
System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Event_Create' expects parameter '@InstallationId', which was not supplied.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at Bit.Infrastructure.Dapper.Repositories.Repository`2.CreateAsync(T obj) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/Repository.cs:line 55
   at Bit.Infrastructure.Dapper.Repositories.EventRepository.CreateAsync(IEvent e) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/EventRepository.cs:line 96
   at Bit.Core.Services.RepositoryEventWriteService.CreateAsync(IEvent e)
   at Bit.Core.Services.EventService.LogCipherEventAsync(Cipher cipher, EventType type, Nullable`1 date)
   at Bit.Core.Services.CipherService.SaveAsync(Cipher cipher, Guid savingUserId, Nullable`1 lastKnownRevisionDate, IEnumerable`1 collectionIds, Boolean skipPermissionCheck, Boolean limitCollectionScope)
   at Bit.Api.Controllers.CiphersController.PutAdmin(String id, CipherRequestModel model) in /home/runner/work/server/server/src/Api/Controllers/CiphersController.cs:line 210
   at lambda_method129(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:78759b5e-40a3-49c5-accb-173b4a00dc72
Error Number:201,State:4,Class:16
2023-02-09 20:21:07.283 +00:00 [Information] Api started.
2023-02-09 20:21:57.770 +00:00 [Error] Procedure or function 'Event_Create' expects parameter '@InstallationId', which was not supplied.
System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Event_Create' expects parameter '@InstallationId', which was not supplied.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at Bit.Infrastructure.Dapper.Repositories.Repository`2.CreateAsync(T obj) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/Repository.cs:line 55
   at Bit.Infrastructure.Dapper.Repositories.EventRepository.CreateAsync(IEvent e) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/EventRepository.cs:line 96
   at Bit.Core.Services.RepositoryEventWriteService.CreateAsync(IEvent e)
   at Bit.Core.Services.EventService.LogCipherEventAsync(Cipher cipher, EventType type, Nullable`1 date)
   at Bit.Core.Services.CipherService.SaveDetailsAsync(CipherDetails cipher, Guid savingUserId, Nullable`1 lastKnownRevisionDate, IEnumerable`1 collectionIds, Boolean skipPermissionCheck)
   at Bit.Api.Controllers.CiphersController.Put(String id, CipherRequestModel model) in /home/runner/work/server/server/src/Api/Controllers/CiphersController.cs:line 190
   at lambda_method97(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:915430a3-6d52-4e19-9b36-c7286cc586a3
Error Number:201,State:4,Class:16
2023-02-09 20:32:13.055 +00:00 [Error] Procedure or function 'Event_Create' expects parameter '@InstallationId', which was not supplied.
System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Event_Create' expects parameter '@InstallationId', which was not supplied.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at Bit.Infrastructure.Dapper.Repositories.Repository`2.CreateAsync(T obj) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/Repository.cs:line 55
   at Bit.Infrastructure.Dapper.Repositories.EventRepository.CreateAsync(IEvent e) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/EventRepository.cs:line 96
   at Bit.Core.Services.RepositoryEventWriteService.CreateAsync(IEvent e)
   at Bit.Core.Services.EventService.LogCipherEventAsync(Cipher cipher, EventType type, Nullable`1 date)
   at Bit.Core.Services.CipherService.SaveDetailsAsync(CipherDetails cipher, Guid savingUserId, Nullable`1 lastKnownRevisionDate, IEnumerable`1 collectionIds, Boolean skipPermissionCheck)
   at Bit.Api.Controllers.CiphersController.Put(String id, CipherRequestModel model) in /home/runner/work/server/server/src/Api/Controllers/CiphersController.cs:line 190
   at lambda_method97(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:bb0a3f92-36ce-4496-b273-a78ec5ecd19c
Error Number:201,State:4,Class:16

Here are my versions:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/63319401/217930975-ac4a45b6-f57a-489d-89c9-069b760afed5.png">

Please let me know if I can add any additional information.
Thanks

**Comment by jlevickas** [comment]
Reinstalled and rebuilt. Working now
