### ISSUE TITLE
License generation fails with latest unified beta

### ISSUE THREAD

**Issue by MokkaSchnalle** [jakeswenson/BitBetter#200]
```
Oops: System.ArgumentNullException: Value cannot be null. (Parameter 'enumType')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Enum.ValidateRuntimeType(Type enumType)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at licenseGen.Program.GenerateOrgLicense(X509Certificate2 cert, String corePath, String userName, String email, Int16 storage, Guid instalId, String businessName, String key) in /licenseGen/Program.cs:line 411
   at licenseGen.Program.<>c__DisplayClass0_1.<Main>b__7() in /licenseGen/Program.cs:line 164
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at licenseGen.Program.Main(String[] args) in /licenseGen/Program.cs:line 305
```

May be related to changes on licensing code by Bitwarden:
[Github Link](https://github.com/bitwarden/server/commit/721d2969d43972d6e2205e4e3fa6b48f16991dda)

Current workaround:
Build Bitbetter for 2024.6.1-beta image tag in order to generate a valid license.
Then change to latest version. Bitwarden accepts the older license.

**Comment by GieltjE** [comment]
Created two pull requests (#201, #202), this seems to be required for non unified builds too.
