### ISSUE TITLE
Error: pull access denied for bitbetter/identity

### ISSUE THREAD

**Issue by xavierxxx** [jakeswenson/BitBetter#25]
Everything ran fine. When going to rebuild bitwarden get the above error. 
Pulling identity (bitbetter/identity:latest)...

Error: pull access denied for bitbetter/identity, repository does not exist or may require 'docker login'

**Comment by JeffAlyanak** [comment]
Hey @xavierxxx, there is no repository for bitbetter/identity, when you run the main build script you are building it locally. After running the build script you should be able to see that new container exists with `docker ps`.

Are you sure that you have successfully built the container first? What return are you getting to the console when you run the `./build.sh`?

**Comment by xavierxxx** [comment]
Hey @JeffAlyanak heres my output. I ran it again. then tried bitwarden again. same error.
```
root@srx88:/home/btyu/BitBetter# ./build.sh
mkdir: cannot create directory ‘./src/bitBetter/.keys’: File exists
cp: cannot stat '.keys/cert.cert': No such file or directory
/home/btyu/BitBetter/src/bitBetter/bitBetter.csproj : warning NU1603: bitBetter depends on Newtonsoft.Json (>= 11.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved.
  Restore completed in 35.38 ms for /home/btyu/BitBetter/src/bitBetter/bitBetter.csproj.
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/home/btyu/BitBetter/src/bitBetter/bitBetter.csproj : warning NU1603: bitBetter depends on Newtonsoft.Json (>= 11.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved.
  Restore completed in 43.61 ms for /home/btyu/BitBetter/src/bitBetter/bitBetter.csproj.
/home/btyu/BitBetter/src/bitBetter/bitBetter.csproj : warning NU1603: bitBetter depends on Newtonsoft.Json (>= 11.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved.
  bitBetter -> /home/btyu/BitBetter/src/bitBetter/bin/Debug/netcoreapp2.0/bitBetter.dll
  bitBetter -> /home/btyu/BitBetter/src/bitBetter/bin/Debug/netcoreapp2.0/publish/
double free or corruption (out)
SIGABRT: abort
PC=0x7fd85a0d3e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc42004bcc0, 0xc42004bce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42004bc90 sp=0xc42004bc50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x16c8990)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc42004bcc0 sp=0xc42004bc90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x16c8990)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc42004bcf8 sp=0xc42004bcc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc4200163b0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc42004bda0 sp=0xc42004bcf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc42004be88, 0x410022, 0xc420016310)
	<autogenerated>:4 +0x46 fp=0xc42004bde0 sp=0xc42004bda0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc42004be68 sp=0xc42004bde0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7fffc986219e, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc42004bed8 sp=0xc42004be68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc42004bf58 sp=0xc42004bed8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc42004bf88 sp=0xc42004bf58
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc42004bfe0 sp=0xc42004bf88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004bfe8 sp=0xc42004bfe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7fffc9860450
rcx    0x7fd85a0d3e97
rdx    0x0
rdi    0x2
rsi    0x7fffc98601e0
rbp    0x7fffc9860550
rsp    0x7fffc98601e0
r8     0x0
r9     0x7fffc98601e0
r10    0x8
r11    0x246
r12    0x7fffc9860450
r13    0x1000
r14    0x0
r15    0x30
rip    0x7fd85a0d3e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Sending build context to Docker daemon  1.467MB
Step 1/4 : FROM bitwarden/api
latest: Pulling from bitwarden/api
Digest: sha256:5f2eb5f6974673bc6f186093ba7706e98ccc9b03a6ac5f5fb96983c699e6ecb5
Status: Image is up to date for bitwarden/api:latest
 ---> 93f9d5912bbd
Step 2/4 : COPY bin/Debug/netcoreapp2.0/publish/* /bitBetter/
 ---> Using cache
 ---> 706140407fe5
Step 3/4 : COPY ./.keys/cert.cert /newLicensing.cer
 ---> Using cache
 ---> 38753b705724
Step 4/4 : RUN dotnet /bitBetter/bitBetter.dll &&     echo "modified dll" &&     mv /app/Core.dll /app/Core.orig.dll &&     mv /app/modified.dll /app/Core.dll &&     echo "replaced dll" &&     rm -rf /bitBetter && rm -rf /newLicensing.cer &&     echo "cleaned up"
 ---> Using cache
 ---> 32f1448871bd
Successfully built 32f1448871bd
Successfully tagged bitbetter/api:latest
```

**Comment by JeffAlyanak** [comment]
Hey @xavierxxx , are you certain that you've got the latest version of BitBetter there? You have some other issues there — it seems the signing cert/key are not generated in the correct directory — but most importantly it looks a lot like it's running an older version of the build script.

**Comment by xavierxxx** [comment]
I followed straight from the readme page here. Ok now Im seeing the readme page is showing "online stuff" not this repo. git clone https://github.com/online-stuff/BitBetter.git

Will change and reinstall

**Comment by JeffAlyanak** [comment]
> I followed straight from the readme page here. Ok now Im seeing the readme page is showing "online stuff" not this repo. git clone https://github.com/online-stuff/BitBetter.git
> 
> Will change and reinstall

Hey xavierxxx, that `git clone` line is a typo introduced by merging a fork. Please clone from *this* repository and not from that fork.

```bash
git clone https://github.com/online-stuff/BitBetter.git
```

**Comment by JeffAlyanak** [comment]
@JeffAlyanak This typo needs to be fixed as soon as possible.

**Comment by JeffAlyanak** [comment]
Typo fix (https://github.com/jakeswenson/BitBetter/pull/23/commits/19d3949b9d431adbe6a6c1ea904fa23e722503e4) has been merged to [master](https://github.com/jakeswenson/BitBetter/tree/master) branch in PR https://github.com/jakeswenson/BitBetter/pull/23.
