### ISSUE TITLE
Identity container not running

### ISSUE THREAD

**Issue by OllieD** [jakeswenson/BitBetter#33]
Followed the instructions using the auto build script and also tried creating my own cert.
Api container seems to run fine but my Identity container just keeps restarting with the below error:

` Parameter name: certificate
      at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddSigningCredential(IIdentityServerBuilder builder, X509Certificate2 certificate)
      at Bit.Core.Utilities.ServiceCollectionExtensions.AddCustomIdentityServerServices(IServiceCollection services, IHostingEnvironment env, GlobalSettings globalSettings)
      at Bit.Identity.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/server/src/Identity/Startup.cs:line 61
	  --- End of stack trace from previous location where exception was thrown ---
      at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
      at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
      at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
      at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
      at Bit.Identity.Program.Main(String[] args) in /home/appveyor/projects/server/src/Identity/Program.cs:line 13`

Running Bitwarden using Docker on Synology DSM 6.2 (Xpenology)
Any help would be appreciated 😊

**Comment by JeffAlyanak** [comment]
Did this get solved?

**Comment by OllieD** [comment]
Yeah thank you for checking,

I believe it was an issue with the latest synology docker package.

I downgraded the package and its working fine now.

Kind regards,

Ollie

**Comment by JeffAlyanak** [comment]
Okay, good to hear.

It's at least worthwhile to know that Synology DSM 6.2 has some issue with our build process. What version did you downgrade to that worked?

**Comment by OllieD** [comment]
My identity.pfx also had the wrong permissions.
I will do some testing when I can and confirm whether it's a non issue
(user error) or the synology package.

I'll let you know once I've had chance to test.

**Comment by JeffAlyanak** [comment]
Thanks, that's much appreciated!

**Comment by OllieD** [comment]
This other comment on a Synology thread about this specific issue mentions
it affects Bitwarden:

https://community.synology.com/enu/forum/1/post/128146?reply=407628

Seems like environment variables aren't being passed to containers on the
Synology Docker Package 18.09.0-505 version

I have manually downgraded to version 17.05.0-0401 from here:

https://archive.synology.com/download/Package/spk/Docker/17.05.0-0401/

and this has resolved the problem.

By the looks of it the password for the .pfx is passed as an environment
variable.
That would explain my issue.

So it's a Synology issue rather than a Bitbetter/Bitwarden issue.

Thanks Jeff, Keep up the good work!

Kind regards,

Ollie
