### ISSUE TITLE
Cannot Generate license

### ISSUE THREAD

**Issue by JeffAlyanak** [jakeswenson/BitBetter#4]
Following the instructions in `README.md` allows me to successfully generate a PFX,  build the `bitwarden/api:latest` image and the `bitbetter/licensegen:latest` image.

However, attempting to run the generator with:
```
./src/licenseGen/run.sh /absolute/path/to/cert.pfx
```

Will return the help text from the license generator (not from the run script):

```
Usage:  [options] [command]

Options:
  --cert            cert file
  --core            path to core dll
  -? | -h | --help  Show help information

Commands:
  org
  user

Use " [command] --help" for more information about a command.
```

The documentation on the org and user command don't appear to be complete and I'm unable to get it to return a license.

**Comment by firelook** [comment]
you have to do
/root/github/BitBetter/src/licenseGen/run.sh /root/github/BitBetter org XXX yyy@aaa.com 12345679

obviously XXX , YYY, 123.. are examples => put yours value

**Comment by JeffAlyanak** [comment]
Okay, that gets me a little closer, but now it's giving the following error:

```
Oops: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Attribute.InternalIsDefined(PropertyInfo element, Type attributeType, Boolean inherit)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at bitwardenSelfLicensor.Program.GenerateOrgLicense(X509Certificate2 cert, String corePath, String userName, String email, Guid instalId, String key) in /home/bitwarden/BitBetter/src/licenseGen/Program.cs:line 217
   at bitwardenSelfLicensor.Program.<>c__DisplayClass0_2.<Main>b__7() in /home/bitwarden/BitBetter/src/licenseGen/Program.cs:line 121
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at bitwardenSelfLicensor.Program.Main(String[] args) in /home/bitwarden/BitBetter/src/licenseGen/Program.cs:line 137
```

**Comment by firelook** [comment]
same problem and no clues at all ! ;)

**Comment by JeffAlyanak** [comment]
@firelook @jakeswenson 

I figured out the issue. When building the licensegen, no error will be thrown if the dotnet package for Newtonsoft.net is the wrong version, it'll build and show a success message and simply fault when it tries to actually use that package.

Simply installing the correct version and rebuilding licensegen will solve this issue:

`dotnet add package Newtonsoft.Json --version 11.0.0 `

**Comment by firelook** [comment]
root@security:~/dotnet# dotnet add package Newtonsoft.Json --version 11.0.0
Could not find any project in `/root/dotnet/`.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>

**Comment by johnczer** [comment]
Could you please tell me where or if there is actually an organization.json or similar license file generated and where do I find this?  Or is this license somehow added automatically after following these steps. Each time I run through the steps and log back in to see if the generated license was applied it appears that it has not. I also do not see where to upload a license.json if one actually exist. I have spent hours on this and I am sorry but not a coder.  Thanks

**Comment by JeffAlyanak** [comment]
@johnczer What step are you getting to? What output are you seeing when you try to generate the license?

**Comment by johnczer** [comment]
I was actually able to figure this out yesterday but thanks for responding Jeff!  I'm sorry, I shot-gunned this question and wasn't sure I'd get a response since some were fairly older threads. Appreciate the work and the comments to the others you helped which helped me.
